//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int id { get; set; }
        public int sender_id { get; set; }
        public int reciever_id { get; set; }
        public int paper_id { get; set; }
        public string description { get; set; }
    
        public virtual paper paper { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
