//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.Comment_Paper_Question = new HashSet<Comment_Paper_Question>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
        public Nullable<System.TimeSpan> comment_time { get; set; }
        public string description { get; set; }
        public Nullable<bool> mark_read { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Paper_Question> Comment_Paper_Question { get; set; }
    }
}
