//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_Assignment()
        {
            this.topic_teach = new HashSet<topic_teach>();
        }
    
        public int id { get; set; }
        public int section_id { get; set; }
        public int course_id { get; set; }
        public int user_id { get; set; }
        public int session_id { get; set; }
    
        public virtual course course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<topic_teach> topic_teach { get; set; }
        public virtual section section { get; set; }
        public virtual session session { get; set; }
        public virtual User User { get; set; }
    }
}
