//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Difficulty_level_policy
    {
        public int id { get; set; }
        public int course_id { get; set; }
        public Nullable<int> eassy_Q { get; set; }
        public Nullable<int> medium_Q { get; set; }
        public Nullable<int> difficult_Q { get; set; }
        public string term { get; set; }
        public Nullable<int> session_id { get; set; }
    
        public virtual course course { get; set; }
        public virtual session session { get; set; }
    }
}
