//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DirectorDashboardEntities : DbContext
    {
        public DirectorDashboardEntities()
            : base("name=DirectorDashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<clo> cloes { get; set; }
        public virtual DbSet<Clo_Weightage> Clo_Weightage { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Comment_Paper_Question> Comment_Paper_Question { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<Course_Assignment> Course_Assignment { get; set; }
        public virtual DbSet<Difficulty_level_policy> Difficulty_level_policy { get; set; }
        public virtual DbSet<paper> papers { get; set; }
        public virtual DbSet<paper_Assignment> paper_Assignment { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Question_Accept_Reject> Question_Accept_Reject { get; set; }
        public virtual DbSet<Question_edited> Question_edited { get; set; }
        public virtual DbSet<Role_Assignment> Role_Assignment { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<submission_period> submission_period { get; set; }
        public virtual DbSet<topic> topics { get; set; }
        public virtual DbSet<topic_teach> topic_teach { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vetting_Timming_Assignment> Vetting_Timming_Assignment { get; set; }
    }
}
