//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paper_Assignment
    {
        public int id { get; set; }
        public int course_id { get; set; }
        public int user_id { get; set; }
        public int session_id { get; set; }
    
        public virtual course course { get; set; }
        public virtual session session { get; set; }
        public virtual User User { get; set; }
    }
}
