//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Comment_Paper_Question = new HashSet<Comment_Paper_Question>();
            this.Question_Accept_Reject = new HashSet<Question_Accept_Reject>();
        }
    
        public int id { get; set; }
        public string text { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string difficulty_level { get; set; }
        public Nullable<int> clo_id { get; set; }
        public Nullable<int> marks { get; set; }
        public int paper_id { get; set; }
        public Nullable<bool> isextra { get; set; }
        public Nullable<int> editor_id { get; set; }
        public Nullable<int> version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Paper_Question> Comment_Paper_Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_Accept_Reject> Question_Accept_Reject { get; set; }
        public virtual User User { get; set; }
        public virtual clo clo { get; set; }
        public virtual paper paper { get; set; }
        public virtual paper paper1 { get; set; }
        public virtual paper paper2 { get; set; }
    }
}
