//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_edited
    {
        public int id { get; set; }
        public string text { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string difficulty_level { get; set; }
        public Nullable<int> clo_id { get; set; }
        public Nullable<int> marks { get; set; }
        public int paper_id { get; set; }
        public Nullable<bool> isextra { get; set; }
        public Nullable<int> editor_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
