//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_clo
    {
        public int id { get; set; }
        public int question_id { get; set; }
        public int clo_id { get; set; }
    
        public virtual clo clo { get; set; }
        public virtual Question Question { get; set; }
    }
}
