//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vetting_Timming_Assignment
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> Vetting_Date { get; set; }
        public Nullable<System.TimeSpan> Vetting_Time { get; set; }
    
        public virtual User User { get; set; }
    }
}
